// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"lqkhoi-go-http-api/internal/models"
)

func newSprint(db *gorm.DB, opts ...gen.DOOption) sprint {
	_sprint := sprint{}

	_sprint.sprintDo.UseDB(db, opts...)
	_sprint.sprintDo.UseModel(&models.Sprint{})

	tableName := _sprint.sprintDo.TableName()
	_sprint.ALL = field.NewAsterisk(tableName)
	_sprint.ID = field.NewInt(tableName, "id")
	_sprint.CreatedAt = field.NewTime(tableName, "created_at")
	_sprint.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sprint.DeletedAt = field.NewField(tableName, "deleted_at")
	_sprint.Name = field.NewString(tableName, "name")
	_sprint.StartDate = field.NewTime(tableName, "start_date")
	_sprint.EndDate = field.NewTime(tableName, "end_date")
	_sprint.ProjectID = field.NewInt(tableName, "project_id")
	_sprint.Goal = field.NewString(tableName, "goal")
	_sprint.Tasks = sprintHasManyTasks{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Tasks", "models.Task"),
		Assignee: struct {
			field.RelationField
			CurrentProject struct {
				field.RelationField
				Manager struct {
					field.RelationField
				}
				Tasks struct {
					field.RelationField
				}
				Sprints struct {
					field.RelationField
					Project struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				TeamMembers struct {
					field.RelationField
				}
			}
			ManagedProjects struct {
				field.RelationField
			}
			AssignedTasks struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Tasks.Assignee", "models.User"),
			CurrentProject: struct {
				field.RelationField
				Manager struct {
					field.RelationField
				}
				Tasks struct {
					field.RelationField
				}
				Sprints struct {
					field.RelationField
					Project struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				TeamMembers struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Tasks.Assignee.CurrentProject", "models.Project"),
				Manager: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Tasks.Assignee.CurrentProject.Manager", "models.User"),
				},
				Tasks: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Tasks.Assignee.CurrentProject.Tasks", "models.Task"),
				},
				Sprints: struct {
					field.RelationField
					Project struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Tasks.Assignee.CurrentProject.Sprints", "models.Sprint"),
					Project: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Tasks.Assignee.CurrentProject.Sprints.Project", "models.Project"),
					},
					Tasks: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Tasks.Assignee.CurrentProject.Sprints.Tasks", "models.Task"),
					},
				},
				TeamMembers: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Tasks.Assignee.CurrentProject.TeamMembers", "models.User"),
				},
			},
			ManagedProjects: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Tasks.Assignee.ManagedProjects", "models.Project"),
			},
			AssignedTasks: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Tasks.Assignee.AssignedTasks", "models.Task"),
			},
		},
		Project: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Tasks.Project", "models.Project"),
		},
		Sprint: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Tasks.Sprint", "models.Sprint"),
		},
	}

	_sprint.Project = sprintBelongsToProject{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Project", "models.Project"),
	}

	_sprint.fillFieldMap()

	return _sprint
}

type sprint struct {
	sprintDo sprintDo

	ALL       field.Asterisk
	ID        field.Int
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Name      field.String
	StartDate field.Time
	EndDate   field.Time
	ProjectID field.Int
	Goal      field.String
	Tasks     sprintHasManyTasks

	Project sprintBelongsToProject

	fieldMap map[string]field.Expr
}

func (s sprint) Table(newTableName string) *sprint {
	s.sprintDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sprint) As(alias string) *sprint {
	s.sprintDo.DO = *(s.sprintDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sprint) updateTableName(table string) *sprint {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.Name = field.NewString(table, "name")
	s.StartDate = field.NewTime(table, "start_date")
	s.EndDate = field.NewTime(table, "end_date")
	s.ProjectID = field.NewInt(table, "project_id")
	s.Goal = field.NewString(table, "goal")

	s.fillFieldMap()

	return s
}

func (s *sprint) WithContext(ctx context.Context) ISprintDo { return s.sprintDo.WithContext(ctx) }

func (s sprint) TableName() string { return s.sprintDo.TableName() }

func (s sprint) Alias() string { return s.sprintDo.Alias() }

func (s sprint) Columns(cols ...field.Expr) gen.Columns { return s.sprintDo.Columns(cols...) }

func (s *sprint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sprint) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["name"] = s.Name
	s.fieldMap["start_date"] = s.StartDate
	s.fieldMap["end_date"] = s.EndDate
	s.fieldMap["project_id"] = s.ProjectID
	s.fieldMap["goal"] = s.Goal

}

func (s sprint) clone(db *gorm.DB) sprint {
	s.sprintDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sprint) replaceDB(db *gorm.DB) sprint {
	s.sprintDo.ReplaceDB(db)
	return s
}

type sprintHasManyTasks struct {
	db *gorm.DB

	field.RelationField

	Assignee struct {
		field.RelationField
		CurrentProject struct {
			field.RelationField
			Manager struct {
				field.RelationField
			}
			Tasks struct {
				field.RelationField
			}
			Sprints struct {
				field.RelationField
				Project struct {
					field.RelationField
				}
				Tasks struct {
					field.RelationField
				}
			}
			TeamMembers struct {
				field.RelationField
			}
		}
		ManagedProjects struct {
			field.RelationField
		}
		AssignedTasks struct {
			field.RelationField
		}
	}
	Project struct {
		field.RelationField
	}
	Sprint struct {
		field.RelationField
	}
}

func (a sprintHasManyTasks) Where(conds ...field.Expr) *sprintHasManyTasks {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sprintHasManyTasks) WithContext(ctx context.Context) *sprintHasManyTasks {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sprintHasManyTasks) Session(session *gorm.Session) *sprintHasManyTasks {
	a.db = a.db.Session(session)
	return &a
}

func (a sprintHasManyTasks) Model(m *models.Sprint) *sprintHasManyTasksTx {
	return &sprintHasManyTasksTx{a.db.Model(m).Association(a.Name())}
}

type sprintHasManyTasksTx struct{ tx *gorm.Association }

func (a sprintHasManyTasksTx) Find() (result []*models.Task, err error) {
	return result, a.tx.Find(&result)
}

func (a sprintHasManyTasksTx) Append(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sprintHasManyTasksTx) Replace(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sprintHasManyTasksTx) Delete(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sprintHasManyTasksTx) Clear() error {
	return a.tx.Clear()
}

func (a sprintHasManyTasksTx) Count() int64 {
	return a.tx.Count()
}

type sprintBelongsToProject struct {
	db *gorm.DB

	field.RelationField
}

func (a sprintBelongsToProject) Where(conds ...field.Expr) *sprintBelongsToProject {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sprintBelongsToProject) WithContext(ctx context.Context) *sprintBelongsToProject {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sprintBelongsToProject) Session(session *gorm.Session) *sprintBelongsToProject {
	a.db = a.db.Session(session)
	return &a
}

func (a sprintBelongsToProject) Model(m *models.Sprint) *sprintBelongsToProjectTx {
	return &sprintBelongsToProjectTx{a.db.Model(m).Association(a.Name())}
}

type sprintBelongsToProjectTx struct{ tx *gorm.Association }

func (a sprintBelongsToProjectTx) Find() (result *models.Project, err error) {
	return result, a.tx.Find(&result)
}

func (a sprintBelongsToProjectTx) Append(values ...*models.Project) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sprintBelongsToProjectTx) Replace(values ...*models.Project) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sprintBelongsToProjectTx) Delete(values ...*models.Project) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sprintBelongsToProjectTx) Clear() error {
	return a.tx.Clear()
}

func (a sprintBelongsToProjectTx) Count() int64 {
	return a.tx.Count()
}

type sprintDo struct{ gen.DO }

type ISprintDo interface {
	gen.SubQuery
	Debug() ISprintDo
	WithContext(ctx context.Context) ISprintDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISprintDo
	WriteDB() ISprintDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISprintDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISprintDo
	Not(conds ...gen.Condition) ISprintDo
	Or(conds ...gen.Condition) ISprintDo
	Select(conds ...field.Expr) ISprintDo
	Where(conds ...gen.Condition) ISprintDo
	Order(conds ...field.Expr) ISprintDo
	Distinct(cols ...field.Expr) ISprintDo
	Omit(cols ...field.Expr) ISprintDo
	Join(table schema.Tabler, on ...field.Expr) ISprintDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISprintDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISprintDo
	Group(cols ...field.Expr) ISprintDo
	Having(conds ...gen.Condition) ISprintDo
	Limit(limit int) ISprintDo
	Offset(offset int) ISprintDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISprintDo
	Unscoped() ISprintDo
	Create(values ...*models.Sprint) error
	CreateInBatches(values []*models.Sprint, batchSize int) error
	Save(values ...*models.Sprint) error
	First() (*models.Sprint, error)
	Take() (*models.Sprint, error)
	Last() (*models.Sprint, error)
	Find() ([]*models.Sprint, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Sprint, err error)
	FindInBatches(result *[]*models.Sprint, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Sprint) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISprintDo
	Assign(attrs ...field.AssignExpr) ISprintDo
	Joins(fields ...field.RelationField) ISprintDo
	Preload(fields ...field.RelationField) ISprintDo
	FirstOrInit() (*models.Sprint, error)
	FirstOrCreate() (*models.Sprint, error)
	FindByPage(offset int, limit int) (result []*models.Sprint, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISprintDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sprintDo) Debug() ISprintDo {
	return s.withDO(s.DO.Debug())
}

func (s sprintDo) WithContext(ctx context.Context) ISprintDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sprintDo) ReadDB() ISprintDo {
	return s.Clauses(dbresolver.Read)
}

func (s sprintDo) WriteDB() ISprintDo {
	return s.Clauses(dbresolver.Write)
}

func (s sprintDo) Session(config *gorm.Session) ISprintDo {
	return s.withDO(s.DO.Session(config))
}

func (s sprintDo) Clauses(conds ...clause.Expression) ISprintDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sprintDo) Returning(value interface{}, columns ...string) ISprintDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sprintDo) Not(conds ...gen.Condition) ISprintDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sprintDo) Or(conds ...gen.Condition) ISprintDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sprintDo) Select(conds ...field.Expr) ISprintDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sprintDo) Where(conds ...gen.Condition) ISprintDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sprintDo) Order(conds ...field.Expr) ISprintDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sprintDo) Distinct(cols ...field.Expr) ISprintDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sprintDo) Omit(cols ...field.Expr) ISprintDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sprintDo) Join(table schema.Tabler, on ...field.Expr) ISprintDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sprintDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISprintDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sprintDo) RightJoin(table schema.Tabler, on ...field.Expr) ISprintDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sprintDo) Group(cols ...field.Expr) ISprintDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sprintDo) Having(conds ...gen.Condition) ISprintDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sprintDo) Limit(limit int) ISprintDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sprintDo) Offset(offset int) ISprintDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sprintDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISprintDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sprintDo) Unscoped() ISprintDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sprintDo) Create(values ...*models.Sprint) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sprintDo) CreateInBatches(values []*models.Sprint, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sprintDo) Save(values ...*models.Sprint) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sprintDo) First() (*models.Sprint, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sprint), nil
	}
}

func (s sprintDo) Take() (*models.Sprint, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sprint), nil
	}
}

func (s sprintDo) Last() (*models.Sprint, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sprint), nil
	}
}

func (s sprintDo) Find() ([]*models.Sprint, error) {
	result, err := s.DO.Find()
	return result.([]*models.Sprint), err
}

func (s sprintDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Sprint, err error) {
	buf := make([]*models.Sprint, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sprintDo) FindInBatches(result *[]*models.Sprint, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sprintDo) Attrs(attrs ...field.AssignExpr) ISprintDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sprintDo) Assign(attrs ...field.AssignExpr) ISprintDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sprintDo) Joins(fields ...field.RelationField) ISprintDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sprintDo) Preload(fields ...field.RelationField) ISprintDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sprintDo) FirstOrInit() (*models.Sprint, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sprint), nil
	}
}

func (s sprintDo) FirstOrCreate() (*models.Sprint, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sprint), nil
	}
}

func (s sprintDo) FindByPage(offset int, limit int) (result []*models.Sprint, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sprintDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sprintDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sprintDo) Delete(models ...*models.Sprint) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sprintDo) withDO(do gen.Dao) *sprintDo {
	s.DO = *do.(*gen.DO)
	return s
}
